version: "3.7"
services:
  ##############################################################
  ###  Backend services:
  ##############################################################
  config-service:
    image: dhub.prm.novobit.eu/webapp/backend/dev/config:dev
    container_name: config-dev
    restart: always
    ports:
      - "8088:8088"
    healthcheck:
      test: ls -la
      interval: 4s
      timeout: 2s
      retries: 3
    networks:
      - cloud-dev
      - prm-be-dev
  ##############################################################
  discovery-service:
    image: dhub.prm.novobit.eu/webapp/backend/dev/discovery:dev
    container_name: discovery-dev
    restart: always
    ports:
      - "8061:8061"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
    healthcheck:
      test: ls -la
      interval: 4s
      timeout: 2s
      retries: 3
    networks:
      - cloud-dev
      - prm-be-dev
    ##############################################################
  gateway-service:
    image: dhub.prm.novobit.eu/webapp/backend/dev/gateway:dev
    container_name: gateway-dev
    restart: always
    ports:
      - "8060:8060"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
    healthcheck:
      test: ls -la
      interval: 4s
      timeout: 2s
      retries: 3
    networks:
      - cloud-dev
      - prm-be-dev
    ##############################################################
    ###  Networks:
    ##############################################################
networks:
  tp-tools:
    name: net-tp-tools
    driver: bridge
  cloud-dev:
    name: net-cloud-dev
    driver: bridge
  prm-fe-dev:
    name: net-prm-fe-dev
    driver: bridge
  prm-be-dev:
    name: net-prm-be-dev
    driver: bridge