version: "3.7"
services:
  ##############################################################
  ###  Kafka/zookeeper:
  ##############################################################
  zookeeper:
    container_name: zookeeper-dev
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - tp-tools
  kafka:
    container_name: NBWBCUBS-PRMKafKa1
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - tp-tools
  minio:
    container_name: minIo
    image: bitnami/minio:latest
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - tp-tools
    volumes:
      - /home/prm/dev/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=novobit.eu
  ##############################################################
  ###  Networks:
  ##############################################################
networks:
  tp-tools:
    name: net-tp-tools
    driver: bridge
  cloud-dev:
    name: net-cloud-dev
    driver: bridge
  prm-fe-dev:
    name: net-prm-fe-dev
    driver: bridge
  prm-be-dev:
    name: net-prm-be-dev
    driver: bridge
  ai-fe-dev:
    name: net-ai-de-dev
    driver: bridge