spring:
  application:
    name: learning-service
    version: @project.version@ #pom: project.version
  banner:
    location: classpath:banner.txt
  config:
    import: "optional:configserver:@cloud.config.service@"
